incorporate csawMG update and pass both intel and GNU RT tests
ufs-community/ccpp-physics pull request #171
Opened 2024-02-13 15:40 UTC by AnningCheng-NOAA

ajor updated CSAW deep convective scheme: considering sigma vertical veriantion and reduction on fluxes instead of tendency etc.
• Regression tests are performed on the new version of CSAW for GNU and intel compilers
Here is a EMail from Don describe the changes:
On Thu, Oct 24, 2019 at 3:01 PM Donald Dazlich - NOAA Affiliate <[donald.dazlich@noaa.gov](mailto:donald.dazlich@noaa.gov)> wrote:
Hi Moorthi, Anning,
Dave and I have been using the GFS version of CS to redo our implementation of AW more completely and consistently. Now, you will find that the fix_form implemetation of the tendencies match up very closely with the traditional form. Also you will notice that it is the fluxes for each cloud type (and the downdraft) that are saved and the reduction is done on the fluxes, not the tendency computed from the flux divergence. Since sigma is a function of height the latter approach is incorrect. I’ve also dimensioned several cloud type variables nctp+1 - the nctp+1 slot has downdraft output. Another addition is the sorting of the lamdas after they are computed for all cloud types, then computing the sigma. This approach is detailed in a manuscript Dave is working on. Also, sigma is not applied to the inputs to the downdraft routine, but to the outputs, which are now mass fluxes not tendencies. The water and thermodynamic budgets remain satisfied now.
I’ve attached my version below. It should be pretty close to your version with regards to the interface so you shouldn’t have to do much work with it.
Regards,
Don

2024-02-15 16:29 UTC, Qingfu-Liu commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +      REAL(kind_phys) :: GTM3MAX = 1._kind_phys
GTM2MAX and GTM3MAX are not used in subroutine CUMCHK, and can be removed or comment out

2024-02-15 16:33 UTC, Qingfu-Liu commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +      REAL(kind_phys)     sigmai (IM,KMAX+1,NCTP), sigma(IM,KMAX+1)   !!DDsigma cloud updraft fraction
Variables sigmai and sigma are not used in SUBROUTINE CUMFXR1, so variables sigmai, sigma and nctp can be removed from SUBROUTINE CUMFXR1

2024-02-15 18:45 UTC, AnningCheng-NOAA commented
Qingfu, nice catch! and fixed.

On Thu, Feb 15, 2024 at 11:33 AM Qingfu Liu ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In physics/CONV/Chikira_Sugiyama/cs_conv.F90
> <https://github.com/ufs-community/ccpp-physics/pull/171#discussion_r1491297802>
> :
>
> > @@ -3841,64 +4083,66 @@ SUBROUTINE CUMFXR1                                   & ! Tracer mass fixer
>          ! 2: mass fixer is applied, total mass never change through cumulus scheme
>          !    e.g. CO2
>        INTEGER      ISTS, IENS
> +      REAL(kind_phys)     sigmai (IM,KMAX+1,NCTP), sigma(IM,KMAX+1)   !!DDsigma cloud updraft fraction
>
> Variables sigmai and sigma are not used in SUBROUTINE CUMFXR1, so
> variables sigmai, sigma and nctp can be removed from SUBROUTINE CUMFXR1
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ufs-community/ccpp-physics/pull/171#pullrequestreview-1883309910>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALQPMIOK4NPVCUOCHWUJOU3YTY2G7AVCNFSM6AAAAABDGXNNRKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOBTGMYDSOJRGA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-02-20 21:22 UTC, dustinswales requested changes
There are lots of whitespace/indentation changes, along with quite a few code changes, making reviewing this difficult. I feel the changes aren't terribly invasive, but it's hard to tell in it's current form. 
It also seems that the [inline documentation for the Chikira-Sugiyama convective scheme was removed](https://dtcenter.ucar.edu/GMTB/v5.0.0/sci_doc/group__cs__scheme.html). This will need to be added back in, and potentially updated with any recent algorithm modifications.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!!
The "!!" are needed for documentation (e.g. https://dtcenter.ucar.edu/GMTB/v5.0.0/sci_doc/group__cs__scheme.html#details), please revert.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +  use machine ,   only : kind_phys
Remove whitespace

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -   real(kind_phys), parameter :: fact1=(cvap-cliq)/rvap, fact2=el/rvap-fact1*t0c !< to calculate d(qs)/dT
I believe the trailing comments should start with "!<". @mzhangw Can you confirm?
I know that lines that start with "!<" are used for documentation, not sure about the case above.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +   logical, intent(in)     :: otspt(1:ntracp1,1:2)! otspt(:,1) - on/off switch for tracer transport by updraft and
This argument should be assumed-shape.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +   real(kind_phys), intent(in)    :: DELTA               ! physics time step
Please revert whitespace changes.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!> -# Following the Relaxed Arakawa Schubert Scheme (RAS;
Restore documentation

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +!  if (lprnt) write(0,*)' aft cs_cum gtql=',gtq(ipr,:,3), clw(sprh, ice,liq,..ntke)
Only line 400 contains a change. Changes to lines 401-407 are whitespace changes only.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!>\ingroup cs_scheme
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +      REAL(kind_phys)     GCTM  ( IJSDIM, KMAX+1 )   !! cloud T (half lev)   !DDsigmadiag make output
Please fix indentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +!    if (.not. allocated(FSCAV))  ALLOCATE (FSCAV(NTR))   !DD made module scope and allocatable
Are these added commented lines needed?

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +       gtt(i,k)     = zero
Please revert whitespace changes.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!> -# Compute layer saturate moisture \f$Q_i\f$(GDQS) and
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +!#ifdef OPT_CHASER
Are these lines needed?

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!> -# Compute tropopause height (GDZTR)
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!> -# Call cumbas() to compute cloud base properties
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +   DO K = 1, KMAX
Please revert whitespace changes.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!> -# Compute CAPE and CIN
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -           IF (BUOY > zero .AND. JBUOY(I) >=  -1) THEN
Please remove whitespace.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -              CIN(I) = CIN(I) - BUOY * GRAV * (GDZM(I,K+1) - GDZM(I,K))
Nice catch!

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!> -# Initialize variables before summing over cloud types
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +   if(flx_form) then
lamdaprod is now only set if this conditional is met. 
If lamdaprod is used downstream, this could cause problems.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!> -# Call cumup() to compute in-cloud properties
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!> -# Call cumbmx() to compute cloud base mass flux
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +     if (flx_form) then
Where does this block terminate?
(I see another if (flx_form) just below?)

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +    endif         ! if (flx_form)
NM. I see it ends down here.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!> -# Call cumflx() to compute cloud mass flux and precipitation
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -   DO CTP=1,NCTP
Please revert whitespace changes

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +!              sfluxtem(:,:,nctp+1) , qvfluxtem(:,:,nctp+1), &  !interface flux, not tendency
Please remove unnecessary comments.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!> -# Call cumsbw() to compute cloud subsidence heating
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +!!
Please remove.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +       GPRCPF( I,K ) = 0.5D0*( GPRCP( I,K )+GPRCP( I,K+1 ) )
GPRCPF is defined as type kind_phys, not double.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -      REAL(kind_phys), dimension(ijsdim,kmax)     :: gctbl, gcqbl, gcwbl, gcqlbl, gcqibl   !>DDsigmadiag
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +!       DO K=KLCLB+1,KBMAX-1
There is no need to comment code like this. Simply removing it is sufficient, since GitHub captures these changes.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!>\ingroup cs_scheme
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -      REAL(kind_phys)   ACWF  (IJSDIM)             !< cloud work function
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!>\ingroup cs_scheme
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!>\ingroup cs_scheme
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!>\ingroup cs_scheme
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!>\ingroup cs_scheme
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!>\ingroup cs_scheme
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +      END SUBROUTINE CUMSBW!***********************************************************************
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!>\ingroup cs_scheme
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +!#ifdef OPT_CHASER
Are these commented directives needed?

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +      REAL(kind_phys)     CUMFRC( IJSDIM )            !! cumulus cloud fraction
Please restore whitesapce and documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!>\ingroup cs_scheme
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +!DD      use ppgrid      , only: IJSDIM => pcols, KMAX => pver
Are these lines needed?

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +              FX(I) = 0.D0
FX is defined as type kind_phys, not double. If FX is intended to be of type double, then it needs to be defined that way. Or you could use real(FX,kind=kind_dbl_prec) where FX is referenced.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +                                * ((1.D0-FX( I))*SBR0 + FX1*SBR1 )
So here to ensure a double precision calculation, 
replace:
1.D0 - FX( I)
with:
1._kind_dbl_prec -  real(FX( I),kind=kind_dbl_prec)

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!>\ingroup cs_scheme
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!>\ingroup cs_scheme
Please restore documentation.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -      REAL(kind_phys)     GTR   (IJSDIM, KMAX)      ! tracer tendency
Please revert whitespace changes.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +            FWAT = 1.D0
See comment on double precision calculations above.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
It was hard to review this module given the amount of whitespace changes included.

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv_aw_adj.F90
> -
Please remove

2024-02-20 21:22 UTC, dustinswales commented on physics/CONV/Chikira_Sugiyama/cs_conv_pre.F90
> -end module cs_conv_pre
Please revert

2024-02-20 21:22 UTC, dustinswales commented on physics/MP/Morrison_Gettelman/m_micro.F90
> -
Please revert.

2024-02-20 21:22 UTC, dustinswales commented on physics/MP/Morrison_Gettelman/m_micro.F90
> -
Please revert.

2024-02-21 00:19 UTC, AnningCheng-NOAA commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> -!!
done. Please check.

2024-02-21 00:19 UTC, AnningCheng-NOAA commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +  use machine ,   only : kind_phys
done. Please check.

2024-02-21 00:19 UTC, AnningCheng-NOAA commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +   logical, intent(in)     :: otspt(1:ntracp1,1:2)! otspt(:,1) - on/off switch for tracer transport by updraft and
done. Please check.

2024-02-21 00:20 UTC, AnningCheng-NOAA commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
> +   real(kind_phys), intent(in)    :: DELTA               ! physics time step
done. Please check.

2024-02-21 00:21 UTC, AnningCheng-NOAA commented on physics/CONV/Chikira_Sugiyama/cs_conv.F90
all done as suggested.

2024-02-21 00:21 UTC, AnningCheng-NOAA commented on physics/MP/Morrison_Gettelman/m_micro.F90
> -
done. Please check.

2024-02-21 02:14 UTC, AnningCheng-NOAA commented
Sorry for those empty lines, coming from debugging or from the old version of the code.

2024-03-06 18:19 UTC, grantfirl commented
@AnningCheng-NOAA I'm going to try to clean up some of the whitespace and documentation changes so that the PR only shows actually meaningful changes. I may open another PR to make it easier to track and ask for you to review.

2024-03-06 18:48 UTC, AnningCheng-NOAA commented
sure. Thank you! @Grant Firl ***@***.***>

On Wed, Mar 6, 2024 at 1:19 PM Grant Firl ***@***.***> wrote:

> @AnningCheng-NOAA <https://github.com/AnningCheng-NOAA> I'm going to try
> to clean up some of the whitespace and documentation changes so that the PR
> only shows actually meaningful changes. I may open another PR to make it
> easier to track and ask for you to review.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ufs-community/ccpp-physics/pull/171#issuecomment-1981516236>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALQPMIL5QYY23TIINMKMAWLYW5M2DAVCNFSM6AAAAABDGXNNRKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOBRGUYTMMRTGY>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-03-07 19:40 UTC, grantfirl commented
Closed in favor of https://github.com/ufs-community/ccpp-physics/pull/181 that started from the top of ufs/dev and has fewer whitespace/comment changes that make it difficult to review and understand the changes.

2024-03-07 19:40 UTC, closed without merging