TO DISCUSS: Feature/gfdlmpv3
ufs-community/ccpp-physics pull request #195
Opened 2024-04-03 21:00 UTC by dustinswales

This PR is intended to supersede #162

@RuiyuSun I refactored to code so that GFDL v1 and v3 share as much common code as possible.

I introduced a new module, module_gfdlmp_parm, which is configured for either v1 or v3, and referenced in fv_sat_adj.F90. 

All of the configuration info is stored in a DDT in module_gfdlmp_parm, with default values in the same location as before, the module_gfdl_### files. After the GFDLMP namelist is read in the type is set. (Having this info gathered in a DDT allows us to make the DDT a CCPP interstitial, which would be handy if we had scheme-to-scheme dependencies that we wanted to pass around)

I also removed the imp_physics_gfdl_v3 flag. GFDL v1 and v3 have their own distinct namelists, so there is no need to have another switch to distinguish v1/v3.
The only differences to run with GFDLv1 or v3 are:
- at the SDF, gfdl_cloud_microphys or gfdl_cloud_microphys_v3 and
- which namelist is added to gfs_phys_nml: ([V1 nml](https://github.com/dustinswales/ccpp-physics/blob/feature/gfdlmpv3/physics/MP/GFDL/v1_2019/module_gfdl_cloud_microphys.F90#L323), [V3 nml](https://github.com/dustinswales/ccpp-physics/blob/feature/gfdlmpv3/physics/MP/GFDL/v3_2022/module_gfdl_cloud_microphys_v3.F90#L529))

2024-04-04 16:19 UTC, RuiyuSun commented
@dustinswales This is great and thanks!! I agree that the scheme name in SDF and different namelist name are enough to distinguish the two versions of the scheme. So I think it is good idea to remove the  imp_physics_gfdl_v3 flag. Did you forget to remove the flag in the gfdl_cloud_microphysics_v3.F90 file? 

What is next?

2024-04-04 17:54 UTC, dustinswales commented
@RuiyuSun Good call. I just removed the flag from the scheme.

Next we need to test that the RTs that use GFDLMP v1 are unchanged (I can do this next week). I can't speak to how the v3 results should differ wrt v1 (I will leave this piece to you)

2024-04-04 17:58 UTC, RuiyuSun commented
> @RuiyuSun Good call. I just removed the flag from the scheme.
> 
> Next we need to test that the RTs that use GFDLMP v1 are unchanged (I can do this next week). I can't speak to how the v3 results should differ wrt v1 (I will leave this piece to you)

@dustinswales Sounds good.

2024-04-09 17:28 UTC, RuiyuSun commented
@dustinswales How do I check out this code? Thanks!

2024-04-09 21:37 UTC, dustinswales commented
> @dustinswales How do I check out this code? Thanks!

git clone --recursive --branch feature/gfdlmpv3 https://github.com/dustinswales/ufs-weather-model.git

2024-04-19 15:11 UTC, grantfirl commented
@dustinswales @RuiyuSun This isn't yet ready to be put in the merge queue, correct?

2024-04-19 15:14 UTC, grantfirl commented
@dustinswales @RuiyuSun Does this supercede #162 so that it can be closed?

2024-04-19 17:06 UTC, dustinswales commented
@grantfirl Yes. #162 can be closed.
More changes coming to this PR in the coming days.

2024-05-03 14:14 UTC, grantfirl commented
@dustinswales @RuiyuSun Will you let us know when this is ready to review and test?

2024-11-18 22:43 UTC, dustinswales commented
@grantfirl This is ready for review.

2025-01-08 16:38 UTC, grantfirl commented on physics/MP/GFDL/module_gfdlmp_param.F90
> +  real(kind_phys) :: tice           = 273.15  !< freezing temperature (K): ref: GFDL, GFS (DJS: V3=273.15)
Why does this need to be redefined from the one that is already provided by the host (temperature_at_zero_celsius)? Does it really make that much of a difference to 1) use a different value for each version and 2) use something different than the host and rest of physics?

2025-01-08 16:49 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3.F90
> +      ! DH* TODO: CLEANUP, all of these should be coming in through the argument list
Yes, and consider the comment RE: temperature_at_zero_celsius

2025-01-08 16:55 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3.F90
> +            if (imp_physics==imp_physics_gfdl) then
Why is this necessary? Shouldn't the check above already have been executed and returned with an error if imp_physics is wrong?

2025-01-08 17:00 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +!* This file is part of the FV3 dynamical core.
It's a little weird to have this in a physics scheme in the CCPP, but I'm guessing that it's not our call.

2025-01-08 17:01 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +    real, parameter :: grav = 9.80665 ! acceleration due to gravity (m/s^2), ref: IFS
Yikes. Lots of redefining constants here. Why does GFDL MP need to have a different gravity or pi than the host or rest of physics?

2025-01-08 17:02 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +    real, parameter :: tice = 273.15 ! freezing temperature (K): ref: GFDL, GFS
This is double redefining. It was redefined in the GFDL MP specific module then redefined here. Why?

2025-01-08 17:06 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +    call mpdrv (hydrostatic, ua, va, wa, delp, pt, qv, ql, qr, qi, qs, qg, qa, &
This is another scheme with 3 layers of drivers. Not ideal, but I assume that there is a good reason to keep all of them?

2025-01-08 17:08 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +    convt = 86400. * rgrav / dts
redefining # of seconds in a day

2025-01-08 17:11 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +                print*, "GFDL-MP-DRY TE: ", &
Consider wrapping print statements with a debug flag to reduce standard out spam for normal execution.

2025-01-08 17:13 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +            print *, "gfdl_mp: qflag error!"
Should one pass down and set ccpp_err_msg and ccpp_err_flag and return? Or is this error not that egregious?

2025-01-08 17:13 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +                            print *, "gfdl_mp: qflag error!"
Same question RE: error handling

2025-01-08 17:14 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +            print *, "gfdl_mp: qflag error!"
Same question RE: error handling

2025-01-08 17:14 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +            print *, "gfdl_mp: qflag error!"
Same question RE: error handling

2025-01-08 17:14 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +            print *, "gfdl_mp: qflag error!"
Ditto

2025-01-08 17:17 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +                    goto 555
GOTOs are generally frowned upon for CCPP schemes. Consider trying to use a different control structure if possible.

2025-01-08 17:19 UTC, grantfirl commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +     te_b = (dte + (lv00 * c_air * vapor - li00 * c_air * (ice + snow + graupel)) * dts / 86400 + sen * dts + stress * dts)
redefining # of seconds in a day again

2025-01-08 17:24 UTC, grantfirl commented
@RuiyuSun @dustinswales I finished my initial review. Mostly minor comments. The biggest things for me are that there are a lot of physical constants being redefined that are introducing potential inconsistencies with the rest of the code base (host and rest of physics) and the potential need to extend CCPP error handling downward into the actual physics code to catch and return errors. Overall, nice job! I don't see anything that absolutely HAS to be changed, although addressing my comments would definitely help CCPP compatibility.

2025-01-08 20:00 UTC, grantfirl requested changes
I'm putting a "request changes" review on this. I'm not saying that all my comments need to lead to code changes -- explanations for why they can't change can also suffice, and I'll approve at that time.

2025-01-14 02:39 UTC, dustinswales commented on physics/MP/GFDL/module_gfdlmp_param.F90
> +  real(kind_phys) :: tice           = 273.15  !< freezing temperature (K): ref: GFDL, GFS (DJS: V3=273.15)
@grantfirl These are the defaults and (potentially) overwritten later on. I don't know if the 0.01K difference is by design or an oversight (I didn't want to add any changes when creating this module).
@RuiyuSun Does v3 need tice=273.16? or could we use 273.15?

2025-01-14 16:44 UTC, RuiyuSun commented on physics/MP/GFDL/module_gfdlmp_param.F90
> +  real(kind_phys) :: tice           = 273.15  !< freezing temperature (K): ref: GFDL, GFS (DJS: V3=273.15)
@dustinswales In v3 it is defined as 273.15.

2025-01-14 16:46 UTC, RuiyuSun commented on physics/MP/GFDL/module_gfdlmp_param.F90
> +  real(kind_phys) :: tice           = 273.15  !< freezing temperature (K): ref: GFDL, GFS (DJS: V3=273.15)
According to the comment in the v3 code, 273.15 is used to be consistent with the value defined in other schemes in GFS

2025-01-24 22:27 UTC, dustinswales commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3.F90
> +      ! DH* TODO: CLEANUP, all of these should be coming in through the argument list
done.

2025-01-24 22:28 UTC, dustinswales commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +!* This file is part of the FV3 dynamical core.
My guess is this is a relic from a prior code port. I guess we can leave it for now

2025-01-24 22:28 UTC, dustinswales commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3_mod.F90
> +    real, parameter :: tice = 273.15 ! freezing temperature (K): ref: GFDL, GFS
Fixed.

2025-01-24 22:32 UTC, dustinswales commented
@grantfirl I changed the constants in the ccpp driver to inout arguments. The constants in the scheme module I changed to use the values in physcons. Adding all the "plumbing" to pass the constants around in the scheme is a biggish task, so I went with this. 
I also parameterized the precision in the scheme module.
There is probably more that could be done, but not in this initial PR.

2025-01-29 21:19 UTC, grantfirl approved these changes
I don't love bringing in physcons which means that this scheme can't be used outside of the UFS ecosystem, but if you just want to get this in and worry about it later, that is OK, I guess.

2025-02-04 00:24 UTC, mkavulich reviewed
@dustinswales I started this review a long time ago and never found time to finish it. These are not urgent corrections, so I'll leave them as optional. I didn't want to mark it as "approval" since I didn't finish reviewing the code, but what I got through looked good.

2025-02-04 00:24 UTC, mkavulich commented on physics/MP/GFDL/module_gfdlmp_param.F90
> +  real(kind_phys) :: qi_gen         = 1.82e-6 !< (v1/v3) max cloud ice generation during remapping step (V1 ONLY. Computed internally in V3)
```suggestion
  real(kind_phys) :: qi_gen         = 1.82e-6 !< max cloud ice generation during remapping step (V1 ONLY. Computed internally in V3)
```

2025-02-04 00:24 UTC, mkavulich commented on physics/MP/GFDL/module_gfdlmp_param.F90
> +  logical :: const_vw               = .false. !< if .ture., the constants are specified by v * _fac
```suggestion
  logical :: const_vw               = .false. !< if .true., the constants are specified by v * _fac
```

2025-02-04 00:24 UTC, mkavulich commented on physics/MP/GFDL/module_gfdlmp_param.F90
> +                                              !< 3: Marshall-Palmer formula (https://en.wikipedia.org/wiki/DBZ_(meteorology))
More authoritative source. Could also just state "Marshall and Palmer 1948"
```suggestion
                                              !< 3: Marshall-Palmer formula (https://glossary.ametsoc.org/wiki/Marshall-palmer_relation)
```

2025-02-04 00:24 UTC, mkavulich commented on physics/MP/GFDL/module_gfdlmp_param.F90
> +                                              !< 3: Marshall-Palmer formula (https://en.wikipedia.org/wiki/DBZ_(meteorology))
```suggestion
                                              !< 3: Marshall-Palmer formula (https://glossary.ametsoc.org/wiki/Marshall-palmer_relation)
```

2025-02-04 00:24 UTC, mkavulich commented on physics/MP/GFDL/module_gfdlmp_param.F90
> +                                              !< 3: Marshall-Palmer formula (https://en.wikipedia.org/wiki/DBZ_(meteorology))
```suggestion
                                              !< 3: Marshall-Palmer formula (https://glossary.ametsoc.org/wiki/Marshall-palmer_relation)
```

2025-02-04 00:24 UTC, mkavulich commented on physics/MP/GFDL/module_gfdlmp_param.F90
> +          write (6, *) 'gfdl - mp :: invalid scheme version number'
```suggestion
          write (6, *) 'gfdl - mp :: invalid scheme version number', version
```
I always like error messages to echo the invalid parameter

2025-02-04 00:24 UTC, mkavulich commented on physics/MP/GFDL/v3_2022/gfdl_cloud_microphys_v3.F90
> +      water0     = 0
```suggestion
      water0    = 0
```

2025-02-07 15:50 UTC, grantfirl commented
@dustinswales I'm not sure whether you want to address some of the changes for @mkavulich or go ahead with this PR as-is. Please let me know.

2025-02-19 19:03 UTC, rhaesung approved these changes

2025-02-20 15:25 UTC, dustinswales commented
@grantfirl @mkavulich This is ready to go as is.
There is more that could be done, but I can't take it on at the moment.

2025-02-21 14:51 UTC, grantfirl commented
> @grantfirl @mkavulich This is ready to go as is. There is more that could be done, but I can't take it on at the moment.

OK, I'll try to get this into the queue.

2025-02-21 14:56 UTC, RuiyuSun approved these changes
Thanks@dustinswales

2025-03-03 20:16 UTC, Qingfu-Liu approved these changes

2025-07-14 19:17 UTC, merged