UFS-SRW v3.0.0 SciDoc updates
ufs-community/ccpp-physics pull request #80
Opened 2023-06-08 15:45 UTC by mzhangw

It is to initialize scientific documentation update for UFS-SRW v3.0.0 release from DTC.

2023-06-08 21:37 UTC, mkavulich commented
I am worried about the size of these images; ideally there should be *no* binary files (images included) in a github repository, especially for one that is a submodule for many other repositories. 5MB may not seem like a lot but that is an extra 5MB every time the repository is cloned, and it increases the entire ccpp-physics repository size by ~15%. And if we continue adding images for every new capability this problem will only get worse.

Is there a way for us to host these images elsewhere instead of keeping them in the ccpp-physics repository?

2023-06-09 17:56 UTC, ligiabernardet commented
@mzhangw Pls provide la link to the rendered html so we can use as part of the review. Tks

@mkavulich Good point. What do you suggest? I suppose it could be distributed as a release asset??

2023-06-14 14:25 UTC, ligiabernardet commented
Thanks for collecting these updates.
Given how extensive the changes described in the .txt files are, is the inline documentation contained in the Fortran files still current or does it need to be updated?

- index.html
  - app -> App
  - Please add an explanation to say that the GFS v16 suite is not the same code as the operational GFS v16 code uses. First because GFS v16 does not use CCPP at all. Second because the code has marched ahead. Similarly, the code in the all other suites has evolved, so the RAP suite/param is not what the operational RAP uses. Then say that P8 is like P8A (not the final P8) but also with evolved schemes. I suggest repeating this info on the page for each suite.
- rap_suite_page.html: Currently, the RAP suite is supported in SCM only. (not correct)
- _r_r_f_s_v1beta_page.html
   - The RRFS_v1beta suite is the primary suite target for the upcoming operational implementation of the Rapid Refresh Forecast System (RRFS) (not correct. The operational RRFS v1 will use RUC LSM and may use GF. Say that this WAS the primary target but that things have evolved since then)
   -  which is used in the UFS SRW App -> which can be configured using the UFS SRW App
- HRRR and RAP suite: you can add that these are candidates for RRFS v1 operational implementation
- _wo_f_s_v0_page.html
    -  targeted for use in the upcoming operational implementation of the NOAA's Warn-on-Forecast System (WoFS) and for the RRFS ensemble. 
- c_l_m__l_a_k_e_model.html
   - Define acronyms at first occurrence
   -  **The** CLM lake model...
   -  It also computes 2-m temperature: Of the air?? That is surprising to me.
   - in the regional application of UFS (RRFS) -> in the UFS SRW App
   - To cold-start the CLM lake model in RRFS -. To cold-start the CLM lake model in the UFS SRW App
   - The differences of surface variables from the RRFS 6-h forecast -> The differences of surface variables from the experimental RRFS 6-h forecast
- RUC LSM
   - some of these recent modifications -> some of these modifications
   - The sensitivity of surface fluxes and turbine-height winds to the RUC LSM parameters has been explored by Geng Xia, NREL. This study will determine the uncertainty range for the selected parameters in the RUC LSM and will be described in the journal paper. -> The sensitivity of surface fluxes and turbine-height winds to the RUC LSM parameters has been explored by Geng Xia, NREL to determine the uncertainty range for the selected parameters in the RUC LSM.
   -NOAH LSM -> Noah LSM
- NoahMP LSM
   - It is not necessary to describe how to cite the reference. People can click on the link and go see how to cite. However, the citation in the CCPP SciDoc differs from what is recommended in the text. Should it be changed to be as shown in the "how to cite"?
- GF
   - In GF scale awareness, and the aerosol dependence through rain generation (following Berry (1968) [[28]](https://dtcenter.ucar.edu/GMTB/UFS_SRW_App_v3.0.0p/sci_doc/citelist.html#CITEREF_berry_1968) and evaporation formulations (following Jiang et al. (2010) [[102]](https://dtcenter.ucar.edu/GMTB/UFS_SRW_App_v3.0.0p/sci_doc/citelist.html#CITEREF_Jiang_2010) ), depending on the cloud concentration nuclei at cloud base were added. -> The GF scheme takes into account aerosol dependence through rain generation (following Berry (1968) [[28]](https://dtcenter.ucar.edu/GMTB/UFS_SRW_App_v3.0.0p/sci_doc/citelist.html#CITEREF_berry_1968) and evaporation formulations (following Jiang et al. (2010) [[102]] (https://dtcenter.ucar.edu/GMTB/UFS_SRW_App_v3.0.0p/sci_doc/citelist.html#CITEREF_Jiang_2010) ), depending on the cloud concentration nuclei at cloud base. (No need to mention scale awareness here- it is discussed later in this paragraph)
   - GF included -> The GF scheme includes
   - massflux -> mass flux
   - PDF's -> PDFs
   - The deep and congestus convection considers scale awareness (Arakawa et al. (2011) [[8]](https://dtcenter.ucar.edu/GMTB/UFS_SRW_App_v3.0.0p/sci_doc/citelist.html#CITEREF_Arakawa_2011) ), the shallow convection is not scale-aware. -> The deep and congestus convection considers scale awareness (Arakawa et al. (2011) [[8]](https://dtcenter.ucar.edu/GMTB/UFS_SRW_App_v3.0.0p/sci_doc/citelist.html#CITEREF_Arakawa_2011) ). However, the shallow convection is not scale-aware.
   - Aerosol dependence is implemented through dependence of rain generation and evaporation formulations depending on the cloud concentration nuclei at cloud base (Berry 1968 [[28]](https://dtcenter.ucar.edu/GMTB/UFS_SRW_App_v3.0.0p/sci_doc/citelist.html#CITEREF_berry_1968), Jiang et al.(2010) [[102]](https://dtcenter.ucar.edu/GMTB/UFS_SRW_App_v3.0.0p/sci_doc/citelist.html#CITEREF_Jiang_2010), and Lee and Feingold (2010) [[115]](https://dtcenter.ucar.edu/GMTB/UFS_SRW_App_v3.0.0p/sci_doc/citelist.html#CITEREF_lee_and_feingold_2010) ). Not needed??? Already mentioned previously in this paragraph??
   - Aerosol dependence is considered experimental and is turned off at this point. -> Aerosol dependence is considered experimental and is not supported in this release. This should be mentioned earlier in the paragraph, when aerosol-dependence is introduced.
   - CCPP v6.0.0. I recommend incorporating info related to all previous releases into the main text. Then just describe the changes for the current distribution (SRW v3)
   - Operational Impacts in RAP/HRRR -> Why is this under "Physics Updates"? The last RAP/HRRR op impl was a while back.
   - Updates for aerosol-awareness (I suggest removing this since it seems it is not supported in the App)

I may have more comments later.

2023-06-14 19:20 UTC, mkavulich commented
@mzhangw Can you also include a change in `physics/docs/pdftxt/suite_input.nml.txt`? Currently the section for `imp_physics` shows the default value as 99 but does not describe what this default is, can you add its description (should be `Zhao-Carr/Sundqvist microphysics cloud` I believe)?

@ligiabernardet I am not 100% sure (the doxygen documentation is unclear), but it should be possible to point to external images when building documents with Doxygen, using the syntax`@image html https://example.com/image.jpg`. We could host these images by uploading them to a page on the [Github wiki](https://github.com/ufs-community/ccpp-physics/wiki); this is what we have done for hosting some large images for the UFS SRW App users guide.

Thanks!

2023-06-30 19:41 UTC, mkavulich commented
@mzhangw I opened a PR to your branch (https://github.com/mzhangw/ccpp-physics/pull/7) with changes that would move the images to an external location. I did a test locally to make sure it would work the way I expected in doxygen and it looks like it does. Let me know if you have any questions.

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    d_con = 1.0
In RRFS we use d_con=0.5

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    hord_tr = 10
RRFS uses:    hord_dp = 6
    hord_mt = 6
    hord_tm = 6
    hord_tr = 8
    hord_vt = 6

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    n_sponge = 24
In RRFS:
n_sponge = 9

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    nord_tr = 2
In RRFS:
nord_tr=0

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    nrows_blend = 10
In RRFS nrows_blend = 20

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    rf_cutoff = 2000.0
In RRFS:    rf_cutoff = 2000.0
                  **sg_cutoff = 10000.0**

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +&gfs_physics_nml
RRFS rfus with smoke. Add extra lines:    
    addsmoke_flag = 1
    aero_dir_fdb = .true.
    aero_ind_fdb = .false.

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    dspheat            = .true.
In RRFS add after this line:    do_plumerise = .true.
    do_tofd = .false.
    do_ugwp = .false.
    do_ugwp_v0 = .false.
    do_ugwp_v0_nst_only = .false.
    do_ugwp_v0_orog_only = .false.
    drydep_opt = 1
    do_plumerise = .true.
    do_tofd = .false.
    do_ugwp = .false.
    do_ugwp_v0 = .false.
    do_ugwp_v0_nst_only = .false.
    do_ugwp_v0_orog_only = .false.
    drydep_opt = 1

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    effr_in            = .true.
add after this line:    enh_mix = .true.

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    fhlwr              = 1200.0
In RRFS:    fhlwr = 900.0
    fhswr = 900.0

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    iaer               = 5111
iaer = 1011

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    ialb               = 1
ialb=2

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    iems               = 1
iems=2

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    iovr               = 3
After iovr:   
    isncond_opt = 2
    isncovr_opt = 3

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    lwhtr              = .true.
Insert here:    
    mix_chem = .true.
    mosaic_lu = 1
    mosaic_soil = 1

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    nst_anl            = .true.
nst lines could be removed

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    redrag             = .true.
Add:    
    rrfs_sd = .true.
    rrfs_smoke_debug = .false.

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    shal_cnv           = .false.
add:
    smoke_forecast = 0

2023-07-13 22:30 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/FV3_HRRR_input.nml
> +    use_ufo            = .true.
Add:     
wetdep_ls_opt = 1

2023-07-13 22:33 UTC, tanyasmirnova commented on physics/docs/pdftxt/RE300/namelists/input.nml.v21.FV3_HRRR
> +&fv_core_nml
same changes here as in the previous FV3_HRRR

2023-07-18 15:32 UTC, mkavulich requested changes
@mzhangw Can you please merge the changes to remove the large images from this PR? If you have any questions please let me know.

2023-07-20 14:57 UTC, mkavulich commented
Since Man is now on leave, we have re-opened this PR at #91 

@tanyasmirnova Thank you for your comments, I will reach out to you to make sure these get addressed.

2023-07-20 14:58 UTC, closed without merging