add SPP support for G-F deep convection
ufs-community/ccpp-physics pull request #98
Opened 2023-08-21 19:35 UTC by JiliDong-NOAA

This PR is co-authored with Georg Grell and @haiqinli, including:
1. add stochastic parameterization perturbations to Grell-Freitas deep convection parameterization
2. fix reproducibility issue in G-F deep convection at high resolutions (ichoice option switched to 0)
Related PRs for FV3 and ufs-weather-model will be submitted shortly.

2023-08-21 19:41 UTC, haiqinli approved these changes

2023-08-23 14:03 UTC, Qingfu-Liu approved these changes

2023-08-23 14:42 UTC, dustinswales requested changes
Looks good. Just a small request.

2023-08-23 14:42 UTC, dustinswales commented on physics/cu_gf_driver.F90
> +         spp_wts_cu_deep_tmp=min(max(-1.0, spp_wts_cu_deep(i,1)),1.0)
It's best to be explicit with the types you are passing to intrinsics.
Replace min(max(-1.0, spp_wts_cu_deep(i,1)),1.0)
With min(max(-1.kind_phys, spp_wts_cu_deep(i,1)),1._kind_phys)

2023-08-23 15:41 UTC, JiliDong-NOAA commented on physics/cu_gf_driver.F90
> +         spp_wts_cu_deep_tmp=min(max(-1.0, spp_wts_cu_deep(i,1)),1.0)
updated as requested. Thanks for the suggestion @dustinswales

2023-08-23 15:59 UTC, dustinswales approved these changes
@JiliDong-NOAA Thanks for making this change.

2023-08-30 16:43 UTC, grantfirl approved these changes

2023-09-08 15:15 UTC, zach1221 commented
@grantfirl testing is complete on ufs-wm PR #1876. Are you able to merge this PR?

2023-09-08 15:21 UTC, merged